trigger:
- '*'

pool:
  vmImage: 'macOS-latest'

variables:
  scheme: 'WhiteLabel'
  distributionMethod: 'development'
  xcodeProjectPath: '$(Build.SourcesDirectory)/WhiteLabel.xcodeproj'

steps:
- checkout: self

- task: DownloadSecureFile@1
  name: appstoreApiKey
  inputs:
    secureFile: 'AppStoreConnectAPIKey.json'

- script: ls -R $(Build.SourcesDirectory)
  displayName: 'Print directory structure'

- script: |
    sudo gem install cocoapods
    pod install
  displayName: 'CocoaPods install'
  workingDirectory: $(xcodeProjectPath)

- script: |
    sudo gem install fastlane -NV
    fastlane ios fetch_certificates api_key_path:$(appstoreApiKey.secureFilePath)
  displayName: 'Run Fastlane to fetch certificates'
  workingDirectory: $(xcodeProjectPath)
  env:
    FASTLANE_USER: $(FASTLANE_USER)
    FASTLANE_PASSWORD: $(FASTLANE_PASSWORD)
  
- script: |
    sudo gem install fastlane -NV
    fastlane ios release_alpha config:WHITELABELSSX_DEV
  displayName: 'Run Fastlane to release alpha'
  workingDirectory: $(xcodeProjectPath)
  env:
    FASTLANE_USER: $(FASTLANE_USER)
    FASTLANE_PASSWORD: $(FASTLANE_PASSWORD)

- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: $(scheme)
    sdk: 'iphoneos'
    configuration: 'Release'
    xcodeVersion: 'default' 

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop'
    publishLocation: 'Container'
