trigger:
- develop

pool:
  vmImage: 'macOS-latest'

variables:
  scheme: 'WhiteLabel'
  distributionMethod: 'development'
  xcodeProjectPath: '$(Build.SourcesDirectory)/WhiteLabel.xcodeproj'

steps:
- checkout: self

- script: ls -R $(Build.SourcesDirectory)
  displayName: 'Print directory structure'

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'Certificate.p12'
    certPwd: '$(P12_PASSWORD)'
    keychain: 'temp'
  
- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'Development_br.com.systemsat.whitelabelssx.mobileprovision'
  displayName: 'Install Apple Provisioning Profile'

- script: |
    cd $(xcodeProjectPath)
    sudo gem install cocoapods
    pod update
    pod install
  displayName: 'CocoaPods install'
  
- task: Xcode@5
  inputs:
    actions: 'clean build'
    xcWorkspacePath: '**/*.xcworkspace' 
    scheme: $(scheme)
    sdk: 'iphoneos'
    configuration: 'Release'
    xcodeVersion: 'default' 
    packageApp: true
    archivePath: 'output/ipa'
    signingOption: 'auto'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop'
    publishLocation: 'Container'