trigger:
- master

pool:
  vmImage: 'macOS-10.15' # macOS is needed for iOS builds

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.6'
    addToPath: true

- script: |
    sudo gem install bundler
    bundle install
  displayName: 'Install dependencies'

- script: |
    bundle exec fastlane release_alpha config:WHITELABELSSX_DEV
  displayName: 'Run Fastlane'
  env: 
    FASTLANE_USER: $(FASTLANE_USER) # Replace with your Fastlane username
    FASTLANE_PASSWORD: $(FASTLANE_PASSWORD) # Replace with your Fastlane password
