trigger:
- '*'

pool:
  vmImage: 'macOS-latest'

variables:
  scheme: 'WhiteLabel'
  distributionMethod: 'development'
  xcodeProjectPath: '$(Build.SourcesDirectory)/WhiteLabel.xcodeproj'

steps:
- checkout: self

- script: ls -R $(Build.SourcesDirectory)
  displayName: 'Print directory structure'

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'cert.p12'
    certPwd: 'password'
    keychain: 'temp'
    deleteCert: true

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'profile.mobileprovision'

- script: |
    sudo gem install cocoapods
    pod install
  displayName: 'CocoaPods install'
  workingDirectory: $(xcodeProjectPath)

- script: |
    sudo gem install fastlane -NV
    fastlane ios fetch_certificates
  displayName: 'Run Fastlane'

- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: $(scheme)
    sdk: 'iphoneos'
    configuration: 'Release'
    xcodeVersion: 'default' 

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop'
    publishLocation: 'Container'
