trigger:
- develop

pool:
  vmImage: 'macOS-latest'

variables:
  scheme: 'WhiteLabel'
  xcWorkspacePath: '$(Build.SourcesDirectory)/WhiteLabel.xcworkspace'
  IPA_NAME: 'WhiteLabel'
  APP_VERSION: '14'
  targets:
    - name: 'whitelabel'
      infoPlistPath: '$(Build.SourcesDirectory)/WhiteLabel/whitelabel/Info.plist'
    - name: 'whitelabelcopy'
      infoPlistPath: '$(Build.SourcesDirectory)/WhiteLabel/whitelabelcopy/Info.plist'

steps:
- checkout: self

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'CertificatesDistribution.p12'
    certPwd: '$(P12_PASSWORD)'
    keychain: 'temp'
  
- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'DistributionWhiteLabel.mobileprovision'
  displayName: 'Install Apple Provisioning Profile'

- script: |
    cd $(Build.SourcesDirectory)
    pod update
    pod install
  displayName: 'CocoaPods install'

- script: |
    rm -rf ~/Library/Developer/Xcode/DerivedData/
    xcodebuild clean
  displayName: 'Clean Xcode data'

- ${{ each target in variables.targets }}:
  - script: |
      echo "Processing target: ${{ target.name }}"
      
      echo "---- Info.plist BEFORE any updates ----"
      cat ${{ target.infoPlistPath }}

      chmod 644 ${{ target.infoPlistPath }}
      /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $(BUNDLE_ID)" ${{ target.infoPlistPath }}

      current_version=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" ${{ target.infoPlistPath }})
      new_version=$((APP_VERSION + 1))
      /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $new_version" ${{ target.infoPlistPath }}
      
      xcodebuild archive -workspace $(xcWorkspacePath) -scheme ${{ target.name }} \
      -archivePath $(Build.SourcesDirectory)/build/${{ target.name }}.xcarchive
      
      rm -rf $(Build.ArtifactStagingDirectory)/$IPA_NAME-${{ target.name }}.ipa
      xcodebuild -exportArchive -archivePath $(Build.SourcesDirectory)/build/${{ target.name }}.xcarchive \
      -exportOptionsPlist $(Build.SourcesDirectory)/ExportOptions.plist \
      -exportPath $(Build.ArtifactStagingDirectory)/
      
      echo "---- Info.plist AFTER updates ----"
      cat ${{ target.infoPlistPath }}
      
      if [ ! -f $(Build.ArtifactStagingDirectory)/$IPA_NAME-${{ target.name }}.ipa ]; then
          echo "Error: IPA not found for target ${{ target.name }}!"
          exit 1
      fi
      
      mkdir tempIPA_${{ target.name }}
      unzip $(Build.ArtifactStagingDirectory)/$IPA_NAME-${{ target.name }}.ipa -d tempIPA_${{ target.name }}/
      /usr/libexec/PlistBuddy -c "Print CFBundleVersion" tempIPA_${{ target.name }}/Payload/${{ target.name }}.app/Info.plist
      
      retry_count=0
      max_retries=3
      while [ $retry_count -lt $max_retries ]
      do
        xcrun altool --upload-app --type ios --file $(Build.ArtifactStagingDirectory)/$IPA_NAME-${{ target.name }}.ipa --username $(APPLE_DEVELOPER_USERNAME) --password $(APPLE_DEVELOPER_PASSWORD) && break
        retry_count=$((retry_count+1))
        echo "Retry $retry_count/$max_retries..."
        sleep 10
      done
      if [ $retry_count -eq $max_retries ]; then
        echo "Failed to upload after $max_retries attempts. Exiting..."
        exit 1
      fi
    displayName: 'Process and Upload Target: ${{ target.name }}'
