trigger:
- develop

pool:
  vmImage: 'macOS-latest'

variables:
  scheme: 'WhiteLabel'
  xcWorkspacePath: '$(Build.SourcesDirectory)/WhiteLabel.xcworkspace'

steps:
- checkout: self

- script: ls -R $(Build.SourcesDirectory)
  displayName: 'Print directory structure'

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'Certificates.p12'
    certPwd: '$(P12_PASSWORD)'
    keychain: 'temp'
  
- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'DevelopmentWhiteLabel.mobileprovision'
  displayName: 'Install Apple Provisioning Profile'

- script: |
    cd $(Build.SourcesDirectory)
    pod update
    pod install
  displayName: 'CocoaPods install'

- script: rm -rf ~/Library/Developer/Xcode/DerivedData/
  displayName: 'Clean Derived Data'

- script: echo 'Clean build folder' && xcodebuild clean
  displayName: 'Clean Build Folder'

# Debugging Steps (Optional)
- script: echo $(xcWorkspacePath)
  displayName: 'Print xcWorkspacePath'
  
- script: ls -la $(Build.SourcesDirectory)
  displayName: 'List files in source directory'

- script: xcodebuild -list -workspace $(xcWorkspacePath)
  displayName: 'List Available Schemes'
  
- script: |
    security find-identity -v -p codesigning
  displayName: 'List installed certificates'
  
- task: Xcode@5
  inputs:
    actions: 'clean build'
    xcWorkspacePath: '$(xcWorkspacePath)'
    scheme: '$(scheme)'
    sdk: 'iphoneos'
    configuration: 'Development'
    useXcpretty: false
    signingOption: 'manual'
    signingIdentity: '$(CODE_SIGN_IDENTITY)'
    provisioningProfileUUID: '$(APPLE_PROV_PROFILE_UUID)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop'
    publishLocation: 'Container'

- script: ls -R $(Build.SourcesDirectory)/
  displayName: 'Debug: List files in specified directory'

- script: ls -R $(Build.SourcesDirectory)
  displayName: 'Debug: List all files from source directory'

- script: |
    xcodebuild archive -workspace $(xcWorkspacePath) -scheme $(scheme) \
    -archivePath $(Build.SourcesDirectory)/build/WhiteLabel.xcarchive
  displayName: 'Archive Project'

- script: |
    xcodebuild -exportArchive -archivePath $(Build.SourcesDirectory)/build/WhiteLabel.xcarchive \
    -exportOptionsPlist $(Build.SourcesDirectory)/ExportOptions.plist \
    -exportPath $(Build.ArtifactStagingDirectory)/WhiteLabel.ipa
  displayName: 'Archive and export .ipa'

- script: |
    xcrun altool --upload-app -f $(Build.ArtifactStagingDirectory)/WhiteLabel.ipa \
    -u $(APPLE_DEVELOPER_USERNAME) -p $(APPLE_DEVELOPER_PASSWORD)
  displayName: 'Upload to TestFlight'