trigger:
- develop

pool:
  vmImage: 'macOS-latest'

variables:
  scheme: 'WhiteLabel'
  xcWorkspacePath: '$(Build.SourcesDirectory)/WhiteLabel.xcworkspace'
  IPA_NAME: 'WhiteLabel.ipa'
  APP_VERSION: '14'

steps:
- checkout: self

# Instalação de Certificados e Perfil de Provisionamento
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'CertificatesDistribution.p12'
    certPwd: '$(P12_PASSWORD)'
    keychain: 'temp'

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'DistributionWhiteLabel.mobileprovision'
  displayName: 'Install Apple Provisioning Profile'

# Preparação do ambiente
- script: |
    cd $(Build.SourcesDirectory)
    pod update
    pod install
  displayName: 'CocoaPods install'

- script: |
    rm -rf ~/Library/Developer/Xcode/DerivedData/
    xcodebuild clean
  displayName: 'Clean Xcode data'

# Verificações
- script: |
    if [ ! -f $(Build.SourcesDirectory)/ExportOptions.plist ]; then
      echo "Error: ExportOptions.plist not found!"
      exit 1
    fi
  displayName: 'Check ExportOptions.plist exists'

- script: |
    # Ensure Export directory exists and create it if necessary
    mkdir -p $(Build.ArtifactStagingDirectory)/
    
    # Set permissions for Export directory to ensure it's writable
    chmod 755 $(Build.ArtifactStagingDirectory)/

    # Check if Export directory is writable
    if [ ! -d "$(Build.ArtifactStagingDirectory)/" ]; then
        echo "Error: Export directory not found or not writable!"
        exit 1
    fi
  displayName: 'Prepare Export Directory'

# Atualização do Info.plist
- script: |
    infoPlistPath="$(Build.SourcesDirectory)/$(scheme)/Info.plist"
    chmod 644 $infoPlistPath
    /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $(BUNDLE_ID)" $infoPlistPath

    current_version=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" $infoPlistPath)
    new_version=$((APP_VERSION + 1))
    /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $new_version" $infoPlistPath
  displayName: 'Update Info.plist'

# Arquivo e Exportação
- script: |      
    # Archiving
    echo "Arquivando $(scheme)..."
    xcodebuild archive -workspace $(xcWorkspacePath) -scheme $(scheme) \
    -archivePath $(Build.SourcesDirectory)/build/$(scheme).xcarchive

    # Check .xcarchive generation
    ARCHIVE_PATH="$(Build.SourcesDirectory)/build/$(scheme).xcarchive"
    if [ ! -d "$ARCHIVE_PATH" ]; then
        echo "Erro: Arquivo .xcarchive não encontrado após o arquivamento!"
        exit 1
    fi

    # Export to create IPA from .xcarchive
    echo "Exportando IPA para $(scheme)..."
    xcodebuild -exportArchive -archivePath $ARCHIVE_PATH \
    -exportOptionsPlist $(Build.SourcesDirectory)/ExportOptions.plist \
    -exportPath $(Build.ArtifactStagingDirectory)/

    # List contents of the export directory
    echo "Listando conteúdo do diretório de exportação..."
    ls -la $(Build.ArtifactStagingDirectory)/

    # Check for IPA directly
    IPA_PATH="$(Build.ArtifactStagingDirectory)/$(scheme).ipa"
    if [ ! -f "$IPA_PATH" ]; then
        echo "Erro: IPA não encontrado em $IPA_PATH!"
        exit 1
    else
        echo "IPA encontrado: $IPA_PATH"
    fi
  displayName: 'Archive and Export IPA'

- task: AppStoreRelease@1
  inputs:
    serviceEndpoint: 'App Store Connect'
    releaseTrack: 'TestFlight'
    appIdentifier: 'br.com.systemsat.whitelabelssx'
    appType: 'iOS'
    teamId: 'W8L47TG474'
    teamName: 'Systemsat Solucoes e Consultoria em Comunicacao de Dados Ltda.'
