# This file contains the fastlane.tools configuration

#automation for CI part
require 'base64'
require 'tempfile'
require_relative 'values/bundle_ids'

app_store_connect_api_key(
  key_id: "96KGBK2Q6J", 
  issuer_id: "69a6de84-fb7c-47e3-e053-5b8c7c11a4d1", 
  key_filepath: ENV["appStoreKey.secureFilePath"],
  in_house: false,
)

# Declare getConfig function here
def getConfig(name)
  case name
  when "WHITELABELSSX_DEV"
    return Configs::WHITELABELSSX_DEV
  when "WHITELABELSSX_DEV_COPY"
    return Configs::WHITELABELSSX_DEV_COPY
  else
    return nil
  end
end

fastlane_session_base64 = ENV["FASTLANE_SESSION_BASE64"]

if ENV["FASTLANE_SESSION_BASE64"].nil?
  puts "Error: FASTLANE_SESSION_BASE64 environment variable is not set."
else
  decoded_fastlane_session = Base64.decode64(ENV["FASTLANE_SESSION_BASE64"])
  temp_fastlane_session_file = Tempfile.new('fastlane_session')
  temp_fastlane_session_file.write(decoded_fastlane_session)
  temp_fastlane_session_file.rewind

  ENV["SPACESHIP_SESSION_FILE"] = temp_fastlane_session_file.path
end

#Fastfile scope
default_platform(:ios)

import("./extensions/Building.rb")
import("./extensions/Signing.rb")
import("./extensions/TestFlight.rb")

require_relative 'values/bundle_ids'

platform :ios do

  desc "Create a new app on App Store Connect"
  lane :create_new_app do
    create_app(ENV["APP_NAME"], ENV["APP_BUNDLE"], ENV["APP_TEAMNAME"])
  end

  desc "Create a new app on App Store Connect"
  def create_app(app_name, app_bundle, app_teamName)
    produce(
      username: "ianfag@icloud.com",
      app_identifier: app_bundle,
      app_name: app_name,
      language: "pt-BR",
      skip_itc: false,
      team_name: app_teamName
    )
  end

  desc "Authenticate with AppStoreConnect" 
  lane :auth_app_store_connect do 
    app_store_connect_api_key(
      key_filepath: "./fastlane-ssx/fastlane/AppStoreConnectAPIKey.json",
      duration: 1200, 
      in_house: false)
  end

  private_lane :ensure_app_specific_password_exists do
    unless ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"]
      # UI.user_error!("No FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD environment variable found. Please set it up.")
    end
  end
  
  lane :increment_build_number do
      latest_testflight_build_number = sh("fastlane run latest_testflight_build_number app_identifier:6447273573")
      incremented_build_number = latest_testflight_build_number.to_i + 1
    
      # Agora, use o número incrementado para definir a build atual
      increment_build_number(
        build_number: incremented_build_number,
        xcodeproj: "/Users/ianfagundes/fastlane-ssx/WhiteLabel.xcodeproj" # Substitua pelo caminho correto do seu .xcodeproj
      )
  end
    
end
